services:
  db:
    image: postgres:16
    env_file:
      - .env.development
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password_1234
      POSTGRES_DB: dev_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

  store_service:
    build: ./store_service
    working_dir: /app
    volumes:
      - ./store_service:/app
    env_file:
      - .env.development
    ports:
      - "8001:8000"
    depends_on:
      - db

  inventory_service:
    build: ./inventory_service
    working_dir: /app
    volumes:
      - ./inventory_service:/app
    env_file:
      - .env.development
    ports:
      - "8002:8000"
    depends_on:
      - db

  customer_sim:
    build:
      context: ./customer_sim
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./customer_sim:/app
    depends_on:
      - store_service
      - inventory_service
    environment:
      - ENV=development
    command: ["python", "-m", "app"]

volumes:
  db_data:
